-- table »ý¼º 
CREATE TABLE UMS_USER(
	USERID VARCHAR2(300),
	USERPW VARCHAR2(300),
	USERNAME VARCHAR2(300),
	USERAGE VARCHAR2(3),
	USERPHONE VARCHAR2(11),
	USERADDR VARCHAR2(1000),
	CONSTRAINT USER_PK PRIMARY KEY(USERID)
);

