--한줄 주석
/*
여러줄
주석
 */

--테이블 생성
CREATE TABLE TEST(
	INTDATA NUMBER(4),
	STRDATA VARCHAR2(300)
);

--아래와 같은 형태로 PK를 주면 그 제약조건의 이름은
--SYS~~~~ 식으로 만들어진다.(우리가 관리하기 힘들다)
CREATE TABLE CAR(
	CARNUM VARCHAR2(300) PRIMARY KEY,
	BRAND VARCHAR2(300),
	COLOR VARCHAR2(300),
	PRICE NUMBER(5)
);

--아래 방법을 더 많이 쓰게 된다.
CREATE TABLE CAR(
	CARNUM VARCHAR2(300),
	BRAND VARCHAR2(300),
	COLOR VARCHAR2(300),
	PRICE NUMBER(5),
	CONSTRAINT CAR_PK PRIMARY KEY(CARNUM)
);

--테이블 삭제
DROP TABLE CAR;

--테이블 수정
ALTER TABLE CAR ADD(OWNER VARCHAR2(300));
ALTER TABLE CAR MODIFY(OWNER VARCHAR2(301));

--FK 부여하기
CREATE TABLE OWNER(
	ID VARCHAR2(300),
	NAME VARCHAR2(300),
	PHONE VARCHAR2(300),
	ADDR VARCHAR2(1000),
	CONSTRAINT OWNER_PK PRIMARY KEY(ID)
);
DROP TABLE CAR;
CREATE TABLE CAR(
	CARNUM VARCHAR2(300),
	BRAND VARCHAR2(300),
	COLOR VARCHAR2(300),
	PRICE NUMBER(5),
	ID VARCHAR2(300),
	CONSTRAINT CAR_PK PRIMARY KEY(CARNUM),
	CONSTRAINT CAR_OWNER_FK FOREIGN KEY(ID) REFERENCES OWNER(ID)
);











